Sdkbase2
kbase/kb_sdk pull request #307
Opened 2018-02-26 23:18 UTC by sychan

Remove the build of sdkbase image from kb_sdk, and update the templates so that the base image used in "kb-sdk init" has a parameterized image name and tag.

2018-04-24 20:27 UTC, MrCreosote requested changes
Per Steve, this will need future work so that module inits can use updated base images via setting a config file. Probably needs a standard config file location and either a checked in file or some way to pull a file from a remote location.

This PR provides a basic mechanism for testing/exploring that is not actually usable by a general user as yet.

2018-04-24 20:27 UTC, MrCreosote commented on src/java/us/kbase/mobu/initializer/ModuleInitializer.java
> +		cfg = getConfig(file);
Why split the declaration and initialization?

2018-04-24 20:27 UTC, MrCreosote commented on src/java/us/kbase/mobu/initializer/ModuleInitializer.java
> +		Map<String, String> cfg;
make final

2018-04-24 20:27 UTC, MrCreosote commented on src/java/us/kbase/mobu/initializer/ModuleInitializer.java
> +	private Map<String, String> getConfig(String config_path) throws ModuleInitializerException {
make config_path final

2018-04-24 20:27 UTC, MrCreosote commented on src/java/us/kbase/mobu/initializer/ModuleInitializer.java
> +		System.getenv(KB_DEP) : System.getProperty(KB_DEP);
indent

2018-04-24 20:27 UTC, MrCreosote commented on src/java/us/kbase/mobu/initializer/ModuleInitializer.java
> +	private static final String CFG_LOC ="kb-sdk";
Generally good practice to group the constants and and class variables separately rather than intermixing them

2018-04-24 20:27 UTC, MrCreosote commented on src/java/us/kbase/mobu/initializer/ModuleInitializer.java
> +	static String[] required_configs = {"docker_image", "image_tag"};
make final. Also consider doing

private final static List<String> requiredConfigs = Arrays.asList("x", "y");

2018-04-24 20:27 UTC, MrCreosote commented on src/java/us/kbase/mobu/initializer/ModuleInitializer.java
> +	private static final Map<String,String> default_cfg;
Java norms is to use camelCase for variable names

2018-04-24 20:27 UTC, MrCreosote commented on src/java/us/kbase/mobu/initializer/ModuleInitializer.java
> +	static String[] required_configs = {"docker_image", "image_tag"};
does this need to be accessible to other classes? If not make private.

2018-04-24 20:27 UTC, MrCreosote commented on src/java/us/kbase/mobu/initializer/ModuleInitializer.java
> +		for (String directive: required_configs) {
final String...

2018-04-24 20:27 UTC, MrCreosote commented on src/java/us/kbase/mobu/initializer/ModuleInitializerException.java
> + * @author gaprice@lbl.gov
Er... nope, this isn't true

2018-04-24 20:27 UTC, MrCreosote commented on src/java/us/kbase/mobu/initializer/ModuleInitializerException.java
> +/** Thrown when a configuration is invalid and the service cannot start.
Looks like C&P cruft.

2018-04-24 20:27 UTC, MrCreosote commented on src/java/us/kbase/mobu/initializer/ModuleInitializer.java
> +			if ( config.get(directive) == null) {
Extra space

2018-04-24 20:27 UTC, MrCreosote commented on entrypoint
> +    docker pull kbase/sdkbase2:v1.0
Shouldn't this also be parameterized?

2018-10-25 22:51 UTC, jayrbolton commented
Closing as sdkbase2 is now the default

2018-10-25 22:51 UTC, closed without merging